prepare:
  weather:
    end-date: '2020-08-16'
    forecast-horizon: full
    latitude: 59.334591
    longitude: 18.06324
    model: NCEP_GFS
    reference-time-freq: 6H
    start-date: '2020-06-01'
    variables: Temperature, CloudCover
featurize:
  features:
  - cal_weekday
  - dow
train:
  alpha: 0.5
  bagging_fraction: 0.5
  bagging_freq: 5
  boosting: gbdt
  feature_fraction: 1.0
  lambda_l1: 0.0
  lambda_l2: 0.0
  learning_rate: 0.4
  max_bin: 255
  max_depth: 8
  max_leaves: 64
  min_data_in_leaf: 10
  num_threads: 1
  num_trees: 500
  objective: quantile
  verbose: -1
learning_rate: 0.35
